remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Jeu de dés
description: Le jeu de dés!
show_downloads: false
- jekyll-remote-theme
title: Le jeu de dés
description: Le jeu de dés si prenant que vous voudrez jouer à toutes les occasions!
show_downloads: false
